name: Build Artifacts

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      version:
        description: Name of the uploaded artifact
        type: string
    outputs:
      artifact:
        value: ${{jobs.build.outputs.artifact}}
      version:
        value: ${{jobs.build.outputs.version}}
  push:
    branches: 'main'
    tags-ignore: '*'
    paths-ignore:
      - '.github/**'
      - '.githooks/**'
      - 'LICENSE'
      - 'README.md'

jobs:
  gitversion:
    uses: ./.github/workflows/gitversion.yml
  build:
    runs-on: ubuntu-latest
    needs: gitversion
    outputs:
      artifact: ${{steps.setname.outputs.artifact}}
      version: ${{needs.gitversion.outputs.fullSemVer}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set artifact name
        id: setname
        run: echo "artifact=DutchPickle-${{needs.gitversion.outputs.fullSemVer}}" >> $GITHUB_OUTPUT
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:      
          distribution: temurin      
          java-version: 11
          cache: gradle
      - name: Build
        #working-directory: checker
        run: ./gradlew -PCHECKERVERSION="${{needs.gitversion.outputs.fullSemVer}}" --no-daemon distZip
      - name: Create artifact
        run: |
          mkdir ./build-artifact
          cp ./build/distributions/DutchPickle.zip ./build-artifact/${{steps.setname.outputs.artifact}}.zip
      - name: Upload build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{steps.setname.outputs.artifact}}
          path: ./build-artifact/${{steps.setname.outputs.artifact}}.zip
