name: Build

on: 
  workflow_dispatch:
  workflow_call:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4    
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin      
        java-version: 11
        cache: gradle
    - name: Build
      #working-directory: checker
      run: ./gradlew clean build jacocoTestReport
