on: [pull_request]

jobs:
  TICS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin      
          java-version: 11
          cache: gradle
      - name: Build
      #working-directory: checker
        run: ./gradlew clean build jacocoTestReport
      - name: TICS GitHub Action
        uses: tiobe/tics-github-action@v2
        with:
          projectName: 'DutchPickle'
          ticsConfiguration: 'https://eboit.tiobe.com/tiobeweb/TICS/api/cfg?name=main'
          githubToken: ${{secrets.GITHUB_TOKEN}}
          ticsAuthToken: ${{secrets.EBOIT_ANALYZER_TOKEN}}
          installTics: true
